name: career_craft_2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Itim
      fonts: 
        - asset: assets/fonts/ItimRegular.ttf
          weight: 400
    - family: Lora
      fonts: 
        - asset: assets/fonts/LoraRomanRegular.ttf
          weight: 400
    - family: Abyssinica SIL
      fonts: 
        - asset: assets/fonts/AbyssinicaSILRegular.ttf
          weight: 400
